version: "3.2"
services:
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    volumes:
      - ./db-data/:/home/dynamodblocal/data
    ports:
      - "8042:8000"