package com.atstudio.spacedlearningbot.database.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.atstudio.spacedlearningbot.domain.Category;
import lombok.Data;

import java.util.UUID;

import static java.util.Objects.requireNonNullElseGet;
import static org.apache.commons.lang3.RandomStringUtils.randomAlphanumeric;

@DynamoDBTable(tableName = "Category")
@Data
public class CategoryEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String chatScopedId;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private Long chatId;

    public static CategoryEntity fromCategory(Category category, Long chatId) {
        CategoryEntity result = new CategoryEntity();

        result.setId(requireNonNullElseGet(
                category.getId(),
                () -> UUID.randomUUID().toString()
        ));
        result.setChatScopedId(requireNonNullElseGet(
                category.getChatScopedId(),
                () -> randomAlphanumeric(5))
        );

        result.setChatId(chatId);
        result.setName(category.getName());
        return result;
    }

    public Category toCategory() {
        return new Category()
                .withId(this.id)
                .withChatScopedId(this.chatScopedId)
                .withName(this.name);
    }
}
